In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config

1.15.4


<function numpy.__config__.show()>

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
Z = np.zeros((10,10))
print("%d bytes"%(Z.size*Z.itemsize))

800 bytes


In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
Z = np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
Z = np.arange(10,50)

In [8]:
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
Z = np.arange(0,9).reshape(3,3)

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.random((3,3,3))

array([[[0.09638548, 0.7291538 , 0.05957216],
        [0.06311546, 0.4754597 , 0.3004597 ],
        [0.75439333, 0.38160524, 0.2618772 ]],

       [[0.09640922, 0.16443706, 0.75317669],
        [0.11545229, 0.72514953, 0.20980836],
        [0.24163668, 0.88984683, 0.63943432]],

       [[0.21178959, 0.55202099, 0.24622143],
        [0.92188974, 0.16925404, 0.98112117],
        [0.38295938, 0.77810777, 0.38086281]]])

In [13]:
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max()

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5027483739196034


In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
Z = np.ones((5,5))
Z = np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
0*np.nan

nan

In [18]:
np.nan==np.nan

False

In [19]:
np.inf>np.nan

False

In [20]:
np.nan-np.nan

nan

In [21]:
0.3==3*0.1

False

In [25]:
Z = np.diag(1+np.arange(4),k=-1)#对角线下移一位
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [23]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [26]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [28]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
Z = np.random.random((5,5))
Zmax,Zmin = Z.max(),Z.min()
Z = (Z-Zmin)/(Zmax-Zmin)
print(Z)

[[0.32170764 0.63145875 0.0222498  0.63833119 0.27789757]
 [0.40420431 0.13287023 0.55270771 0.49785731 0.19028556]
 [0.19012169 0.4526165  0.6802673  0.03838768 0.        ]
 [1.         0.63179052 0.47589607 0.54232745 0.54591492]
 [0.41428021 0.64690484 0.11854087 0.74602547 0.28396575]]


In [31]:
color = np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [32]:
Z1 = np.random.random((5,3))
Z2 = np.random.random((3,2))
print(Z1.dot(Z2))

[[1.38055526 1.54110456]
 [1.2116727  1.35985771]
 [0.99530717 1.13750151]
 [1.12422604 1.21886165]
 [0.75725359 0.8867082 ]]


In [35]:
Z = np.arange(8)
Z[3:8] = -Z[3:8]
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7])

In [36]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [37]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\lsz\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\lsz\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [38]:
Z = np.random.uniform(-10,+10,10)#从-10到10随机取样，大小为10
print(Z)
print(np.copysign(np.ceil(np.abs(Z)),Z))#ceil改为最小整数如1.2改为1

[ 5.49344199  7.2281352  -6.42124468  9.61741022  5.04975693  7.66612726
 -1.58614997 -6.44687317 -6.78103536 -0.8148131 ]
[ 6.  8. -7. 10.  6.  8. -2. -7. -7. -1.]


In [39]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1,Z2)

print(np.intersect1d(Z1,Z2))

[1 0 9 3 0 2 2 5 7 2] [3 8 6 3 7 8 8 8 2 5]
[2 3 5 7]


In [43]:
#忽略所有的警告
defalut = np.seterr(all="ignore")
Z = np.ones(1)/0

_ = np.seterr(**defalut)

with np.errstate(divide = "ignore"):
    Z = np.ones(1)/0

In [46]:
np.sqrt(-1)#nan
np.emath.sqrt(-1)#1j

1j

In [57]:
y = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(y)
print(today)
print(tomorrow)

2019-08-06
2019-08-07
2019-08-08


In [60]:
Z = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [61]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*-1

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [63]:
Z = np.random.uniform(0,10,10)
print(Z-Z%1)

[6. 2. 0. 3. 2. 0. 0. 0. 1. 4.]


In [64]:
print(np.floor(Z))

[6. 2. 0. 3. 2. 0. 0. 0. 1. 4.]


In [66]:
print(np.ceil(Z)-1)

[6. 2. 0. 3. 2. 0. 0. 0. 1. 4.]


In [69]:
print(Z.astype(int))

[6 2 0 3 2 0 0 0 1 4]


In [70]:
print(np.trunc(Z))

[6. 2. 0. 3. 2. 0. 0. 0. 1. 4.]


In [72]:
Z = np.zeros(5)
Z += np.arange(5)

In [75]:
def gengrate():
    for x in range(10):
        yield x
Z = np.fromiter(gengrate(),dtype=int,count=-1)#返回一个数组，count
#等于-1代表着所有数据可读，
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
Z = np.linspace(0,1,11,endpoint=False)[1:]#返回11个，第一个为0
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [81]:
Z = np.random.random(10)
Z.sort()
Z

array([0.07052108, 0.21732413, 0.33557011, 0.3540303 , 0.36407035,
       0.37694774, 0.46021793, 0.46584511, 0.64203951, 0.80152626])

小数组中，如何用np.sum更快的方法求和？

In [83]:
Z = np.arange(10)
np.add.reduce(Z)#大约快两倍

45

对于两个随机数组A和B检查他们是否相等 

In [88]:
A = np.random.random(10)
B = np.random.random(10)
print(np.array_equal(A,B))
print(np.allclose(A,B))

False
False


创建一个只读数组 

In [89]:
Z = np.zeros(10)
Z.flags.writeable = False

将笛卡尔坐标下的一个10×2的矩阵转化为极坐标形式 

In [91]:
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan(Y,X)
print(R)
print(T)

[0.77781951 0.96139423 1.25451077 0.35735796 0.6326082  1.06421444
 0.53422836 0.9249381  0.75533946 0.51527905]
[0.34490838 0.47130719 0.77779371 0.25412963 0.510798   0.51840042
 0.33484818 0.14676529 0.47431777 0.07796786]


创建一个长度为10的向量，并将向量中最大的值改为1 

In [92]:
Z = np.random.random(10)
Z[Z.argmax()] = 1

 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 

In [95]:
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),
                           np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

给定两个数组x,y,构造Cauchy矩阵($C_{ij} = 1/(x_i - y_j)$) 

In [98]:
x = np.arange(8)
y = x+0.5
c = 1/np.subtract.outer(x,y)
c

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

打印出每个标量类型的最大值和最小值 

In [99]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


打印出一个数组中所有的数值 

In [102]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

给定标量时如何找到数组中最接近标量的值？ 

In [108]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

23


创建一个位置(x,y) 和颜色为(r,g,b)的结构化数组

In [114]:
Z = np.zeros(10,[('position',[('x',float,1),
                            ('y',float,1)]),
                ('color',[('r',float,1),
                        ('g',float,1),
                        ('b',float,1)])])
Z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

对一个表示坐标形状10,2的随机向量，找到点与点之间的距离 

In [116]:
Z = np.random.random((10,2)) 
X,Y = np.atleast_2d(Z[:,0],Z[:,1])#将数据直接视为2维
D = np.sqrt((X - X.T)**2 + (Y-Y.T)**2)
D

array([[0.        , 0.80722013, 0.79229753, 0.4074534 , 0.34543622,
        1.04280591, 0.64597291, 0.66015574, 0.29141199, 0.14138599],
       [0.80722013, 0.        , 0.08884134, 0.42324503, 0.53522469,
        0.36174853, 0.38940236, 0.15064473, 0.80589385, 0.70216561],
       [0.79229753, 0.08884134, 0.        , 0.39222759, 0.55140853,
        0.30451981, 0.31122422, 0.17288319, 0.82300609, 0.6769477 ],
       [0.4074534 , 0.42324503, 0.39222759, 0.        , 0.28554486,
        0.63645134, 0.27136883, 0.29320728, 0.51423126, 0.28505803],
       [0.34543622, 0.53522469, 0.55140853, 0.28554486, 0.        ,
        0.84528353, 0.54846041, 0.38629618, 0.27181085, 0.32105828],
       [1.04280591, 0.36174853, 0.30451981, 0.63645134, 0.84528353,
        0.        , 0.42797357, 0.47705412, 1.11428475, 0.9125489 ],
       [0.64597291, 0.38940236, 0.31122422, 0.27136883, 0.54846041,
        0.42797357, 0.        , 0.34905904, 0.78548009, 0.50739416],
       [0.66015574, 0.15064473, 0.1728831

In [117]:
import scipy
D = scipy.spatial.distance.cdist(Z,Z)
D

array([[0.        , 0.80722013, 0.79229753, 0.4074534 , 0.34543622,
        1.04280591, 0.64597291, 0.66015574, 0.29141199, 0.14138599],
       [0.80722013, 0.        , 0.08884134, 0.42324503, 0.53522469,
        0.36174853, 0.38940236, 0.15064473, 0.80589385, 0.70216561],
       [0.79229753, 0.08884134, 0.        , 0.39222759, 0.55140853,
        0.30451981, 0.31122422, 0.17288319, 0.82300609, 0.6769477 ],
       [0.4074534 , 0.42324503, 0.39222759, 0.        , 0.28554486,
        0.63645134, 0.27136883, 0.29320728, 0.51423126, 0.28505803],
       [0.34543622, 0.53522469, 0.55140853, 0.28554486, 0.        ,
        0.84528353, 0.54846041, 0.38629618, 0.27181085, 0.32105828],
       [1.04280591, 0.36174853, 0.30451981, 0.63645134, 0.84528353,
        0.        , 0.42797357, 0.47705412, 1.11428475, 0.9125489 ],
       [0.64597291, 0.38940236, 0.31122422, 0.27136883, 0.54846041,
        0.42797357, 0.        , 0.34905904, 0.78548009, 0.50739416],
       [0.66015574, 0.15064473, 0.1728831